version: "3.9"
services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "Aston"
      POSTGRES_USER: "BogatovVI"
      POSTGRES_PASSWORD: "StartTask3"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data